name = "project"
skipFolders = [ "node_modules", ".vscode", "out", "dist", ".vscode-test" ]
skipFiles = [ ".gitignore", "package.json" ]

[[processes]]
id = "o0oyzwrp9q2nbbddccga2co7"
name = "Writing"
tasks = [ ]
